services:
  postgres:
    image: postgres:16
    container_name: aural-solfege-db
    environment:
      POSTGRES_DB: solfege-db
      POSTGRES_USER: solfege
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
