logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/solfege-db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=solfege
spring.datasource.password=123456

# Soundfont loading location
soundfont.path=classpath:soundfonts/grand_piano.sf2
