logging.pattern.console=${CONSOLE_LOG_PATTERN:\
  %green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

spring.datasource.url=jdbc:h2:mem:solfege-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123456
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console