logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}

# Enable the console explicitly
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Tell Hibernate to create or update tables based on your @Entity classes
spring.jpa.hibernate.ddl-auto=none

# Ensure data.sql runs AFTER the tables are created
spring.jpa.defer-datasource-initialization=true

# Force Spring to run the scripts
spring.sql.init.mode=always

# Ensure the database doesn't disappear when the console opens a second connection
spring.datasource.url=jdbc:h2:mem:solfege-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123456